# Generated by Django 5.2.8 on 2025-11-14 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('learner', 'Học viên'), ('admin', 'Quản trị viên'), ('superadmin', 'Super Admin')], help_text='Vai trò của người dùng', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động')], default='active', max_length=8)),
                ('xp', models.BigIntegerField(default=0)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('Japanese', 'Tiếng Nhật'), ('English', 'Tiếng Anh'), ('Vietnamese', 'Tiếng Việt')], max_length=10)),
                ('level', models.CharField(choices=[('Sơ cấp', 'Sơ cấp'), ('Trung cấp', 'Trung cấp'), ('Cao cấp', 'Cao cấp')], default='Sơ cấp', max_length=10)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.course')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['course', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('meaning', models.TextField()),
                ('example', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.lesson')),
            ],
            options={
                'db_table': 'flashcards',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('read', 'Đã đọc'), ('unread', 'Chưa đọc')], default='unread', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_limit', models.IntegerField(blank=True, help_text='tính bằng giây', null=True)),
                ('passed_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.lesson')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Trắc nghiệm'), ('drag_drop', 'Kéo thả'), ('fill_in', 'Điền vào chỗ trống')], max_length=20)),
                ('order_index', models.IntegerField()),
                ('answer', models.JSONField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.quiz')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['quiz', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quiz_answers', models.JSONField()),
                ('status', models.CharField(choices=[('passed', 'Đạt'), ('failed', 'Trượt')], default='failed', max_length=6)),
                ('score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_no', models.IntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_attempts',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối'), ('completed', 'Hoàn thành')], default='pending', max_length=10)),
                ('progress_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_courses',
            },
        ),
        migrations.CreateModel(
            name='UserFlashcard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('remembered', 'Đã nhớ'), ('not_remembered', 'Chưa nhớ')], default='not_remembered', max_length=15)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('next_review_date', models.DateTimeField(blank=True, null=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flashcards', to='api.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_flashcards',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookmark', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to='api.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_lessons',
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['lesson'], name='quizzes_lesson__03d932_idx'),
        ),
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['user'], name='user_course_user_id_67e6bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='userflashcard',
            index=models.Index(fields=['user'], name='user_flashc_user_id_b49250_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userflashcard',
            unique_together={('user', 'flashcard')},
        ),
        migrations.AddIndex(
            model_name='userlesson',
            index=models.Index(fields=['user'], name='user_lesson_user_id_5f56f3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlesson',
            unique_together={('user', 'lesson')},
        ),
    ]
