# Generated by Django 5.2.8 on 2025-12-15 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_flashcard_completed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userflashcard',
            name='user_flashc_user_id_b49250_idx',
        ),
        migrations.RemoveField(
            model_name='userflashcard',
            name='status',
        ),
        migrations.AddField(
            model_name='userflashcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userflashcard',
            name='times_reviewed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userflashcard',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userflashcard',
            name='next_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userflashcard',
            index=models.Index(fields=['user', 'next_review_date'], name='user_flashc_user_id_c5e478_idx'),
        ),
    ]
